### ISSUE TITLE
Epic: Integrate Vault with Routing to use routing's quic-p2p (4-7 days)

### ISSUE THREAD

**Issue by jeanphilippeD** [maidsafe/safe_vault#842]
=> Mock routing (exists but does not have quic_p2p functionality)
  => use real routing with some thing mocked. (Real routing mock stuff we would be able to use it when passing flag (May need to be own feature))
  => Mock - quic-p2p may be used from routing with feature flags.

Tasks (4-7 days):
  - [x] (3-5 days) #878 Routing: Dispatch client events to vaults.
    => Caching info, look up info for address and send client message to outbox, and others to routing + tests.
    => Pass through just look up if we have peer_addr info otherwise send to Vault.
    => Similar to what we do in some of the test?
       Can we simulate quic_p2p client. (Could need to rewrite or add new TestClient to use quic_p2p, super simple one only connect + send message) 
   - [x] (1-2 days) #878 Vault: quic-p2p in vault need to be replace with routing event loop.
     => Simple task
     => Tests? create mock_routing that will send event similarly, but will be only localized so only a few place to change.

Additional Tasks:
 - [x]  #895  Replace mock_routing quic_p2p implementation in Vaults with mock quick_p2p exported from Routing (So test can run with real routing)

----

### Task Meeting

  Option:
   - Keep current vault quic-p2p for client only
   - Or extend routing quic-p2p to support client (simple?)
   - Not necessarily multiple event loop with either option.
   - mpmc channel -> could we use that to listen to one on vault the other in routing => Not option as random receiver get message.
   - Parsec consensus order of seconds.
   - 
  
  Pros:
    - Simpler because only one instance as opposed to 2.
    - Need 2 separate connection / 2 socket ... more heavy.

  Cons:
    - Need message dispatching Client / routing?

  What needs to be done:
  - Implement it: (2 issues one task in routing one in vault, maybe too big for one task in routing.)
    - quic-p2p in vault need to be replace with routing event loop.
      => routing pass quic_p2p event as they are wrapped in an enum to allow also parsec events. Or is it a different channel more complicated in vault side? can combine channel output?  (EventBox accessible so we can just use that as the most straight forward option).
      => small surface in Vault.
      => need to replace quic-p2p channel with routing channel.
      => Configuration? handled by quic-p2p (port/ip address ...)
      => Need to pass from vault to routing at creation.
    - Does routing need mpmc channel (Can be EventBox)
      => Yes, would use to communicate client related events (disconnected, connected, message received)
      => routing need to get the events dispatch to vault channel or routing code.
    - Do dispatch:
      => Receive event check from client or node, if client raise to vault. => Require to know who is client and who is vault, provided by quic-p2p (How? peer_info enum Node/Client on new connection).
      => ConnectedTo (Node or Client)
      => Receive new message only give peer_address.
      => Need to create new map of peer_address -> type.
      => (Routing already contain peer_addresses and connection info).
      => (Still have client, but maybe wanted to remove it.)
      => Should not cause particular complexity.
    - No need to publish routing or parsec and safe_vault used as git dependency yet for the binary that we publish.
    - Testing: mock_quic_p2p in vault, should it use routing mock_quick_p2p. (Maybe some small modification in routing mock to support vaults functionality.) Already exported. Possibly a mock routing that would essentially have similar functionality to vault mock quic_p2p but need different API.
   
  - Other approach: Nothing to do.
    Adam: 
    - Separate quic-p2p: 
        - Seems to require less work compared to the alternative
        - Potential performance impact as there is some overhead of running two separate quic-p2p instance. Could be negligible though. Need to investigate this.
        - Requires two ports
        - Not clear how to handle quic-p2p configs. Seems like we would need two configs - one for the client quic-p2p, the other for routing. In practice the only difference probably is the port, so two configs seems overkill, but then there is no clear way to specify two ports. Could be convention based - `client_port = routing_port + 1`, or similar.
        - Less clear architecturally (see Bart's notes below)
        - Potentially complicates testing (need both mock-quick-p2p and mock-routing, or possibly one mock-quic-p2p and then normal routing with mock-quic-p2p)
    - Use routing only
        - More work. On the other hand, we are going to need to modify routing anyway (parsec integration, changes in the API, ..), and the amount of work to handle client connections doesn't seem to be big
        - Other arguments see Bart's notes below
    
    Bart: 
    - Vaults having their own quic-p2p - seems less clean, as there would be much functionality duplication, also vaults would then occupy at least two endpoints (ports), one for routing (connections to other vaults), one for clients. Having routing deal with accepting connections and then pass some of them to vaults to be handled looks like a more clear-cut division of responsibilities - vaults are then consumers of routing and act upon what they get from routing; there is a single place that deals with accepting connections, and they are dispatched to where they should be handled. (An even more clear division of responsibilities to me was when routing was dealing with passing all the messages, and both clients and vaults were consumers - but this seems to have been abandoned and I'm fine with that.)
    
    JP: 
    - Still not clear what is the better approach. On one side having a single place to send and receive messages(routing quick_p2p) seem sensible, on the other it create coupling that may be unecessary. Also if we have these 2 quick_p2p will it cause us trouble when using mocks (is there work there)? Overall, I'd favor keeping routing the simplest it can be and only dealing with vaults seems a reasonable way to achieve this. I'm also not sure whether having different ip/port for client is a pro (could differentiate trafic at the lowest level) or a con (2 network identifier more complex?). One last consideration that will play big for me is time to market, if we have something that work I'd probably avoid changing it until it is necessary. **Overall maybe that decision can be made once we have integrated routing Parsec and maybe get a clearer picture**

    Qi (haven't joined the full discussion, just put my own pre-mature thoughts here): 
    - I'd agree the key factor here is `time-to-market`. Having vault has its own quic-p2p seems the less affects to the change and allows routing doesn't need to consider the client factors.

**Comment by maqi** [comment]
all sub-tasks got addressed.
