### ISSUE TITLE
Epic: Bugs to fix and refactoring.

### ISSUE THREAD

**Issue by jeanphilippeD** [maidsafe/safe_vault#847]
### Bugs to fix:
 - [x] safe_vault: https://github.com/maidsafe/safe_vault/issues/836  (Handle authorized app permission properly - more fined grained.)

### Refactoring:
 - [ ] XorName refactoring in routing (Needed if used in API, otherwise optional).
 
 - [x] Remove client related code from routing if possible and helpful (optional).
  => Client state / client class
  => Unrelated to authority client.

 - [ ] subcrate in safe-nd repo (not well defined)?

 - [x] Moving away from rust-sodium / safe_crypto

**Comment by maqi** [comment]
As mentioned by Nikita that:
The part of `subcrate in safe-nd repo` was about the XorName type which we thought about moving to its own separate crate (prob. as a subcrate for safe-nd).
However it seems the current option of having simple XorName defined in safe-nd for vaults/clients to use and a separate full-blown XorName type in Routing works quite well, so it is not necessary to move it immediately.
